### ISSUE TITLE
Structure tests fails (maven property missing) with Maven 3.0.5

### ISSUE THREAD

**Issue by cassand** [GoogleCloudPlatform/openjdk-runtime#145] opened 2017-09-01 15:49 UTC
During  `mvn clean install` the following error show up
```
status: Image is up to date for gcr.io/gcp-runtimes/structure_test:latest
2017/09/01 15:00:07 Running tests for file /cfg/openjdk8-structure.yaml
--- FAIL: TestAll (0.21s)
    --- FAIL: TestAll/Command_Test:_correct_java_version_is_installed (0.12s)
        structure_test_v1.go:171: Executing: [java -version]
        structure_test_v1.go:188: stderr: openjdk version "1.8.0_131"
                OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-1~bpo8+1-b11)
                OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
        structure_test.go:56: Expected string 'openjdk version "1\.${openjdk.version.major}.*${openjdk.version.minor}"' not found in error!
    --- FAIL: TestAll/Command_Test:_correct_javac_version_is_installed (0.09s)
        structure_test_v1.go:171: Executing: [javac -version]
        structure_test_v1.go:188: stderr: javac 1.8.0_131
        structure_test.go:56: Expected string 'javac 1\.${openjdk.version.major}.*${openjdk.version.minor}' not found in error!
        structure_test.go:45: Total tests run: 2

```

The generated `target/test-classes/openjdk8-structure.yaml` have the following content:
``` yaml
schemaVersion: 1.0.0

commandTests:
- name: 'correct java version is installed'
  command: ['java', '-version']
  expectedError: ['openjdk version "1\.${openjdk.version.major}.*${openjdk.version.minor}"']
- name: 'correct javac version is installed'
  command: ['javac', '-version']
  expectedError: ['javac 1\.${openjdk.version.major}.*${openjdk.version.minor}']
```

I think that the maven properties `openjdk.version.major` and `openjdk.version.minor` are not correctly set or interpreted by maven.

The issue is also present for the `openjdk9` project

**Comment by aslo** [comment] 2017-09-01 17:04
I can't seem to reproduce. Let's look into this more.

**Comment by cassand** [comment] 2017-09-01 18:09
It seems to be related to the version of Maven.

Maven version 3.0.5 fails whereas the version 3.5.0 succeed to build the project.

**Comment by meltsufin** [comment] 2017-09-01 18:58
I think it's worth investigating this issue, since we don't want the build to fail with newer versions of Maven.

**Comment by aslo** [comment] 2017-09-01 19:11
Should we start using a maven wrapper?

**Comment by meltsufin** [comment] 2017-09-01 19:25
Hmm, that, and/or try to understand what's going on and how to make the build work with both versions.

**Comment by cassand** [comment] 2017-09-01 19:30
It seems that the properties in [openjdk8/pom.xml](https://github.com/GoogleCloudPlatform/openjdk-runtime/blob/master/openjdk8/pom.xml) are not loaded by maven.

I would suspect that the Reactor plugin to be involved in the failure (e.g difference in how the modules are loaded).

**Comment by balopat** [comment] 2017-09-07 15:16
I ran into this as well, so quickly tested it. 
Based on the http://apache.mirrors.lucidnetworks.net/maven/maven-3/ list of latest maven distros:
* 3.0.5: fails 
* 3.1.1: fails
* 3.2.5: fails
* 3.3.9: succeeds
I'm working on a fix now with the Maven enforcer plugin in my PR - will close this one with that.

**Comment by balopat** [comment] 2017-09-07 15:31
https://github.com/GoogleCloudPlatform/openjdk-runtime/pull/134/commits/5e98cd749851cbae188a5d6e2a1dcd4cb9a09bdf - this enforces maven 3.3.x

**Closed** 2017-09-07 22:28 UTC
